import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Image } from "@mantine/core";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:image" content="/kartu.png" />
        <meta property="og:title" content="Minal Aidzin Wal Faidzin" />
        <meta property="og:url" content="https://ucapan.makurostudio.my.id" />
        <meta
          property="og:description"
          content="Malik Sekeluarga Menucapkan Minal Aidzin Wal Faidzin , Mohon Maaf Lahir Dan Batin"
        />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
      </Head>
      <Image src={"/kartu.png"} alt="kartu" />
    </>
  );
}
